version: '3.10.11'
services:
  auth-service:
    build: ./auth_service
    ports:
      - "5001:5001"
    networks:
      - backend

  data-service:
    build: ./data_service
    ports:
      - "5002:5002"
    networks:
      - backend

  analysis-service:
    build: ./analysis_service
    ports:
      - "5003:5003"
    networks:
      - backend

  earth-engine-service:
    build: ./earth_engine_service
    ports:
      - "5004:5004"
    networks:
      - backend
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: biolivar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Evenor2510Tech
    ports:
      - "5432:5432"

networks:
  backend: